spring:
  devtools:
    restart:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

myapp:
  jwtSecret: ${JWT_SECRET}
