server:
  port: 8282
spring:
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mrlanu
      password: pass
      database: dartopia-java
      authentication-database: admin

myapp:
  jwtSecret: nio98282exec3=m=m=a=ExceptionHandlerExceptionResolver=Resolved
  jwtExpirationMs: 86400000

#authorization:
#  token:
#    header:
#      name: Authorization
#      prefix: Bearer
#    secret: hfgry463hf746hf573ydh475fhy5739
#    expiration_time: 3600000

