server:
  port: ${PORT:8282}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cache:
    type: caffeine

myapp:
  jwtExpirationMs: 86400000
  settings:
    server-name: ${SERVER_NAME:test1}
