name: network
description: A network client that uses dio package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cache_client:
    path: ../cache_client
  dio: ^5.4.1
  foundation: ^0.0.5
  models:
    path: ../../../packages/models
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
