name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_frog: ^1.0.1
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.12.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  models:
    path: ../packages/models
  mongo_dart: ^0.9.3
  synchronized: ^3.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
