version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrlanu
      MONGO_INITDB_ROOT_PASSWORD: pass

    ports:
      - 27017:27017
    volumes:
      - dartopia:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mrlanu
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mrlanu:pass@mongo:27017/

volumes:
  dartopia:
    driver: local
